### ISSUE TITLE
Suggestions for plugin release

### ISSUE THREAD

**Issue by cbruno10** [theapsgroup/steampipe-plugin-vsphere#5]
Hey @Bonemind and @graza-io , thanks for creating this plugin! We've reviewed it and have some suggestions before publishing below. If you have any questions, please let me know, thanks!

index.md:
- brand_color should be `#696566`
- For icon_url, you can use `images/plugins/theapsgroup/vsphere.svg`
- For og_image, you can use `images/plugins/theapsgroup/vsphere-social-graphic.png`

`go.mod`
- We've recently released [Steampipe SDK v1.6.1](https://github.com/turbot/steampipe-plugin-sdk/blob/main/CHANGELOG.md). I don't believe this plugin needs any of the features in v1.6.0 and onward, but we'd recommend upgrading as there are some bug fixes in between v1.5.0 and v1.6.1.

`vsphere/utils.go`
- There are two places where we just print out connection errors with debug like messages (https://github.com/theapsgroup/steampipe-plugin-vsphere/blob/master/vsphere/utils.go#L21, https://github.com/theapsgroup/steampipe-plugin-vsphere/blob/master/vsphere/utils.go#L31) and don't return the error. Were the messages leftover from testing? And is the `connect` function setup to handle returning errors OK?

`README.md`
- Not a requirement in the file, but would it be easier if you included a `Makefile`, similar to how we've done in other plugins  (https://github.com/turbot/steampipe-plugin-jira/blob/main/Makefile), and then ask users to run `make` instead of `go build ...`/`mv ...` in the alternate instructions?

Table and column descriptions
- Some of the descriptions seem inconsistent or contain typos:

Different casing of `datastore`, also missing periods at the end of each sentence
```
  > .inspect vsphere.vsphere_datastore
  +-------------+---------+--------------------------------------------------------------------------+
  | column      | type    | description                                                              |
  +-------------+---------+--------------------------------------------------------------------------+
  | accessible  | boolean | Whether this datastore is accessible                                     |
  | capacity    | bigint  | Capacity in bytes                                                        |
  | free        | bigint  | Free space left in bytes                                                 |
  | name        | text    | The name of the datastore                                                |
  | type        | text    | The type of Datastore                                                    |
  | uncommitted | bigint  | How much storage on this datastore has been allocated to guests in bytes |
  +-------------+---------+--------------------------------------------------------------------------+
```

Typo in the word `Curent`:
```
  > .inspect vsphere.vsphere_host
  +--------------+--------+----------------------------------+
  | column       | type   | description                      |
  +--------------+--------+----------------------------------+
  | cpu          | text   | CPU model                        |
  | cpu_cores    | bigint | CPU core count                   |
  | cpu_mhz      | bigint | CPU clock rate in mhz            |
  | cpu_threads  | bigint | CPU thread count                 |
  | cpu_usage    | bigint | Current cpu usage in mhz         |
  | manufacturer | text   | The manufacturer of the hardware |
  | memory       | bigint | Memory in bytes                  |
  | memory_usage | bigint | Curent memory usage in MB        |
  | model        | text   | The model of the hardware        |
  | name         | text   | The host's name                  |
  | num_hbas     | bigint | The number of HBAs connected     |
  | num_nics     | bigint | The number of NICs connected     |
  | status       | text   | The status of the host           |
  | uptime       | bigint | Uptime                           |
  +--------------+--------+----------------------------------+
  ```
  
  Are these descriptions pulled from the vSphere SDK or API, or somewhere else? In general, we prefer to use any descriptions from those sources so we can provide users with accurate, easy to find information. Our (short) list of best practices around table and column descriptions can be found at [Table and Column Descriptions](https://steampipe.io/docs/develop/standards#table-and-column-descriptions).

**Comment by cbruno10** [comment]
Also, while looking through the table code, the list functions didn't use any paging. Does the SDK support pagination today for some or all of the resource list calls?

**Comment by graza-io** [comment]
@cbruno10 thanks we'll get on it :)

**Comment by Bonemind** [comment]
I've merged a pr that should address your points. SDK doesn't seem to support pagination

**Comment by cbruno10** [comment]
Thanks @Bonemind ! I'm closing this issue as v0.0.1 is now released :)
